version: "3.7"
services:
  traefik:
    image: traefik
    container_name: traefik
    restart: always
    extra_hosts: 
      - host.docker.internal:172.17.0.1
    command:
      - --providers.file.directory=/etc/traefik
      - --providers.file.filename=traefik.toml
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    environment:
      - CF_API_EMAIL=${CF_EMAIL}
      - CF_API_KEY=${CF_API_KEY}
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /mnt/tank/appdata/traefik.toml:/etc/traefik/traefik.toml
      - /mnt/tank/appdata/certs/:/certs